; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 47
; Schema: 0
OpCapability Shader
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %10 %14 %17
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %8 "SSBO"
OpName %12 "SSBO"
OpDecorate %7 ArrayStride 28
OpMemberDecorate %8 0 Offset 0
OpDecorate %8 Block
OpDecorate %10 DescriptorSet 0
OpDecorate %10 Binding 0
OpDecorate %10 NonWritable
OpDecorate %10 Restrict
OpDecorate %11 ArrayStride 28
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonReadable
OpDecorate %17 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeVector %5 7
%7 = OpTypeRuntimeArray %6
%8 = OpTypeStruct %7
%9 = OpTypePointer StorageBuffer %8
%10 = OpVariable %9 StorageBuffer
%11 = OpTypeRuntimeArray %6
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeVector %5 3
%16 = OpTypePointer Input %15
%17 = OpVariable %16 Input
%18 = OpTypePointer Input %5
%20 = OpConstant %5 0
%23 = OpConstant %5 28
%25 = OpTypePointer StorageBuffer %6
%28 = OpTypeFloat 32
%29 = OpTypeVector %28 7
%32 = OpConstant %28 1
%33 = OpConstantComposite %29 %32 %32 %32 %32 %32 %32 %32
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %45
%45 = OpLabel
%19 = OpAccessChain %18 %17 %20
%21 = OpLoad %5 %19
%22 = OpIMul %5 %21 %23
%24 = OpUDiv %5 %22 %23
%26 = OpAccessChain %25 %10 %20 %24
%27 = OpLoad %6 %26
%30 = OpBitcast %29 %27
%31 = OpFAdd %29 %30 %33
%34 = OpUDiv %5 %22 %23
%35 = OpBitcast %6 %31
%36 = OpCompositeExtract %5 %35 0
%37 = OpCompositeExtract %5 %35 1
%38 = OpCompositeExtract %5 %35 2
%39 = OpCompositeExtract %5 %35 3
%40 = OpCompositeExtract %5 %35 4
%41 = OpCompositeExtract %5 %35 5
%42 = OpCompositeExtract %5 %35 6
%43 = OpCompositeConstruct %6 %36 %37 %38 %39 %40 %41 %42
%44 = OpAccessChain %25 %14 %20 %34
OpStore %44 %43
OpReturn
OpFunctionEnd

