; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 224
; Schema: 0
OpCapability Shader
OpCapability SparseResidency
OpCapability SampledBuffer
OpCapability ImageBuffer
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %8 %11 %14
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %27 "ByteAddressMask"
OpName %25 "index"
OpName %26 "stride"
OpName %36 "SparseTexel"
OpName %147 ""
OpDecorate %8 DescriptorSet 0
OpDecorate %8 Binding 0
OpDecorate %11 DescriptorSet 0
OpDecorate %11 Binding 0
OpDecorate %11 NonReadable
OpDecorate %14 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeImage %5 Buffer 0 0 0 1 Unknown
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%9 = OpTypeImage %5 Buffer 0 0 0 2 R32ui
%10 = OpTypePointer UniformConstant %9
%11 = OpVariable %10 UniformConstant
%12 = OpTypeVector %5 3
%13 = OpTypePointer Input %12
%14 = OpVariable %13 Input
%15 = OpTypePointer Input %5
%17 = OpConstant %5 0
%20 = OpConstant %5 6
%23 = OpConstant %5 16
%24 = OpTypeFunction %5 %5 %5
%30 = OpConstant %5 4294967295
%34 = OpConstant %5 4
%35 = OpTypeVector %5 4
%36 = OpTypeStruct %5 %35
%39 = OpTypeBool
%44 = OpConstant %5 1
%51 = OpConstant %5 2
%58 = OpConstant %5 3
%71 = OpConstant %5 5
%84 = OpConstant %5 7
%91 = OpConstant %5 8
%98 = OpConstant %5 9
%105 = OpConstant %5 10
%112 = OpConstant %5 11
%119 = OpConstant %5 12
%126 = OpConstant %5 13
%133 = OpConstant %5 14
%140 = OpConstant %5 15
%145 = OpTypeFloat 32
%146 = OpTypeVector %145 16
%147 = OpTypeStruct %146 %5
%171 = OpTypeVector %5 16
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %220
%220 = OpLabel
%16 = OpAccessChain %15 %14 %17
%18 = OpLoad %5 %16
%19 = OpShiftLeftLogical %5 %18 %20
%21 = OpLoad %6 %8
%22 = OpIMul %5 %18 %23
%33 = OpFunctionCall %5 %27 %22 %34
%37 = OpImageSparseFetch %36 %21 %33
%38 = OpCompositeExtract %5 %37 0
%40 = OpImageSparseTexelsResident %39 %38
%41 = OpCompositeExtract %5 %37 1 0
%43 = OpIAdd %5 %33 %44
%42 = OpImageSparseFetch %36 %21 %43
%45 = OpCompositeExtract %5 %42 0
%46 = OpImageSparseTexelsResident %39 %45
%47 = OpLogicalAnd %39 %40 %46
%48 = OpCompositeExtract %5 %42 1 0
%50 = OpIAdd %5 %33 %51
%49 = OpImageSparseFetch %36 %21 %50
%52 = OpCompositeExtract %5 %49 0
%53 = OpImageSparseTexelsResident %39 %52
%54 = OpLogicalAnd %39 %47 %53
%55 = OpCompositeExtract %5 %49 1 0
%57 = OpIAdd %5 %33 %58
%56 = OpImageSparseFetch %36 %21 %57
%59 = OpCompositeExtract %5 %56 0
%60 = OpImageSparseTexelsResident %39 %59
%61 = OpLogicalAnd %39 %54 %60
%62 = OpCompositeExtract %5 %56 1 0
%64 = OpIAdd %5 %33 %34
%63 = OpImageSparseFetch %36 %21 %64
%65 = OpCompositeExtract %5 %63 0
%66 = OpImageSparseTexelsResident %39 %65
%67 = OpLogicalAnd %39 %61 %66
%68 = OpCompositeExtract %5 %63 1 0
%70 = OpIAdd %5 %33 %71
%69 = OpImageSparseFetch %36 %21 %70
%72 = OpCompositeExtract %5 %69 0
%73 = OpImageSparseTexelsResident %39 %72
%74 = OpLogicalAnd %39 %67 %73
%75 = OpCompositeExtract %5 %69 1 0
%77 = OpIAdd %5 %33 %20
%76 = OpImageSparseFetch %36 %21 %77
%78 = OpCompositeExtract %5 %76 0
%79 = OpImageSparseTexelsResident %39 %78
%80 = OpLogicalAnd %39 %74 %79
%81 = OpCompositeExtract %5 %76 1 0
%83 = OpIAdd %5 %33 %84
%82 = OpImageSparseFetch %36 %21 %83
%85 = OpCompositeExtract %5 %82 0
%86 = OpImageSparseTexelsResident %39 %85
%87 = OpLogicalAnd %39 %80 %86
%88 = OpCompositeExtract %5 %82 1 0
%90 = OpIAdd %5 %33 %91
%89 = OpImageSparseFetch %36 %21 %90
%92 = OpCompositeExtract %5 %89 0
%93 = OpImageSparseTexelsResident %39 %92
%94 = OpLogicalAnd %39 %87 %93
%95 = OpCompositeExtract %5 %89 1 0
%97 = OpIAdd %5 %33 %98
%96 = OpImageSparseFetch %36 %21 %97
%99 = OpCompositeExtract %5 %96 0
%100 = OpImageSparseTexelsResident %39 %99
%101 = OpLogicalAnd %39 %94 %100
%102 = OpCompositeExtract %5 %96 1 0
%104 = OpIAdd %5 %33 %105
%103 = OpImageSparseFetch %36 %21 %104
%106 = OpCompositeExtract %5 %103 0
%107 = OpImageSparseTexelsResident %39 %106
%108 = OpLogicalAnd %39 %101 %107
%109 = OpCompositeExtract %5 %103 1 0
%111 = OpIAdd %5 %33 %112
%110 = OpImageSparseFetch %36 %21 %111
%113 = OpCompositeExtract %5 %110 0
%114 = OpImageSparseTexelsResident %39 %113
%115 = OpLogicalAnd %39 %108 %114
%116 = OpCompositeExtract %5 %110 1 0
%118 = OpIAdd %5 %33 %119
%117 = OpImageSparseFetch %36 %21 %118
%120 = OpCompositeExtract %5 %117 0
%121 = OpImageSparseTexelsResident %39 %120
%122 = OpLogicalAnd %39 %115 %121
%123 = OpCompositeExtract %5 %117 1 0
%125 = OpIAdd %5 %33 %126
%124 = OpImageSparseFetch %36 %21 %125
%127 = OpCompositeExtract %5 %124 0
%128 = OpImageSparseTexelsResident %39 %127
%129 = OpLogicalAnd %39 %122 %128
%130 = OpCompositeExtract %5 %124 1 0
%132 = OpIAdd %5 %33 %133
%131 = OpImageSparseFetch %36 %21 %132
%134 = OpCompositeExtract %5 %131 0
%135 = OpImageSparseTexelsResident %39 %134
%136 = OpLogicalAnd %39 %129 %135
%137 = OpCompositeExtract %5 %131 1 0
%139 = OpIAdd %5 %33 %140
%138 = OpImageSparseFetch %36 %21 %139
%141 = OpCompositeExtract %5 %138 0
%142 = OpImageSparseTexelsResident %39 %141
%143 = OpLogicalAnd %39 %136 %142
%144 = OpCompositeExtract %5 %138 1 0
%149 = OpBitcast %145 %41
%150 = OpBitcast %145 %48
%151 = OpBitcast %145 %55
%152 = OpBitcast %145 %62
%153 = OpBitcast %145 %68
%154 = OpBitcast %145 %75
%155 = OpBitcast %145 %81
%156 = OpBitcast %145 %88
%157 = OpBitcast %145 %95
%158 = OpBitcast %145 %102
%159 = OpBitcast %145 %109
%160 = OpBitcast %145 %116
%161 = OpBitcast %145 %123
%162 = OpBitcast %145 %130
%163 = OpBitcast %145 %137
%164 = OpBitcast %145 %144
%165 = OpCompositeConstruct %146 %149 %150 %151 %152 %153 %154 %155 %156 %157 %158 %159 %160 %161 %162 %163 %164
%148 = OpCompositeConstruct %147 %165 %38
%166 = OpCompositeExtract %5 %148 1
OpSelectionMerge %222 None
OpBranchConditional %143 %221 %222
%221 = OpLabel
%167 = OpCompositeExtract %146 %148 0
%168 = OpLoad %9 %11
%169 = OpIMul %5 %18 %23
%170 = OpFunctionCall %5 %27 %169 %34
%172 = OpBitcast %171 %167
%173 = OpCompositeExtract %5 %172 0
%174 = OpCompositeExtract %5 %172 1
%175 = OpCompositeExtract %5 %172 2
%176 = OpCompositeExtract %5 %172 3
%177 = OpCompositeExtract %5 %172 4
%178 = OpCompositeExtract %5 %172 5
%179 = OpCompositeExtract %5 %172 6
%180 = OpCompositeExtract %5 %172 7
%181 = OpCompositeExtract %5 %172 8
%182 = OpCompositeExtract %5 %172 9
%183 = OpCompositeExtract %5 %172 10
%184 = OpCompositeExtract %5 %172 11
%185 = OpCompositeExtract %5 %172 12
%186 = OpCompositeExtract %5 %172 13
%187 = OpCompositeExtract %5 %172 14
%188 = OpCompositeExtract %5 %172 15
%189 = OpCompositeConstruct %35 %173 %173 %173 %173
OpImageWrite %168 %170 %189
%190 = OpCompositeConstruct %35 %174 %174 %174 %174
%191 = OpIAdd %5 %170 %44
OpImageWrite %168 %191 %190
%192 = OpCompositeConstruct %35 %175 %175 %175 %175
%193 = OpIAdd %5 %170 %51
OpImageWrite %168 %193 %192
%194 = OpCompositeConstruct %35 %176 %176 %176 %176
%195 = OpIAdd %5 %170 %58
OpImageWrite %168 %195 %194
%196 = OpCompositeConstruct %35 %177 %177 %177 %177
%197 = OpIAdd %5 %170 %34
OpImageWrite %168 %197 %196
%198 = OpCompositeConstruct %35 %178 %178 %178 %178
%199 = OpIAdd %5 %170 %71
OpImageWrite %168 %199 %198
%200 = OpCompositeConstruct %35 %179 %179 %179 %179
%201 = OpIAdd %5 %170 %20
OpImageWrite %168 %201 %200
%202 = OpCompositeConstruct %35 %180 %180 %180 %180
%203 = OpIAdd %5 %170 %84
OpImageWrite %168 %203 %202
%204 = OpCompositeConstruct %35 %181 %181 %181 %181
%205 = OpIAdd %5 %170 %91
OpImageWrite %168 %205 %204
%206 = OpCompositeConstruct %35 %182 %182 %182 %182
%207 = OpIAdd %5 %170 %98
OpImageWrite %168 %207 %206
%208 = OpCompositeConstruct %35 %183 %183 %183 %183
%209 = OpIAdd %5 %170 %105
OpImageWrite %168 %209 %208
%210 = OpCompositeConstruct %35 %184 %184 %184 %184
%211 = OpIAdd %5 %170 %112
OpImageWrite %168 %211 %210
%212 = OpCompositeConstruct %35 %185 %185 %185 %185
%213 = OpIAdd %5 %170 %119
OpImageWrite %168 %213 %212
%214 = OpCompositeConstruct %35 %186 %186 %186 %186
%215 = OpIAdd %5 %170 %126
OpImageWrite %168 %215 %214
%216 = OpCompositeConstruct %35 %187 %187 %187 %187
%217 = OpIAdd %5 %170 %133
OpImageWrite %168 %217 %216
%218 = OpCompositeConstruct %35 %188 %188 %188 %188
%219 = OpIAdd %5 %170 %140
OpImageWrite %168 %219 %218
OpBranch %222
%222 = OpLabel
OpReturn
OpFunctionEnd
%27 = OpFunction %5 None %24
%25 = OpFunctionParameter %5
%26 = OpFunctionParameter %5
%28 = OpLabel
%29 = OpUDiv %5 %30 %26
%31 = OpBitwiseAnd %5 %25 %29
OpReturnValue %31
OpFunctionEnd

