; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 177
; Schema: 0
OpCapability Shader
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %9 %13 %18 %21
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpName %16 "SSBO"
OpName %33 "ByteAddressMask"
OpName %31 "index"
OpName %32 "stride"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %15 ArrayStride 64
OpMemberDecorate %16 0 Offset 0
OpDecorate %16 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 0
OpDecorate %13 NonReadable
OpDecorate %13 Aliased
OpDecorate %18 DescriptorSet 0
OpDecorate %18 Binding 0
OpDecorate %18 NonReadable
OpDecorate %18 Aliased
OpDecorate %21 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeVector %5 16
%15 = OpTypeRuntimeArray %14
%16 = OpTypeStruct %15
%17 = OpTypePointer StorageBuffer %16
%18 = OpVariable %17 StorageBuffer
%19 = OpTypeVector %5 3
%20 = OpTypePointer Input %19
%21 = OpVariable %20 Input
%22 = OpTypePointer Input %5
%24 = OpConstant %5 0
%27 = OpConstant %5 6
%29 = OpConstant %5 16
%30 = OpTypeFunction %5 %5 %5
%36 = OpConstant %5 4294967295
%40 = OpConstant %5 4
%41 = OpTypePointer StorageBuffer %5
%46 = OpConstant %5 1
%50 = OpConstant %5 2
%54 = OpConstant %5 3
%61 = OpConstant %5 5
%66 = OpTypeVector %5 7
%68 = OpTypeFloat 32
%69 = OpTypeVector %68 7
%72 = OpConstant %5 28
%75 = OpConstant %5 7
%99 = OpTypeVector %68 16
%103 = OpConstant %5 64
%122 = OpTypePointer StorageBuffer %14
%125 = OpConstant %5 4096
%128 = OpConstant %5 1024
%152 = OpConstant %5 8192
%154 = OpConstant %5 128
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %175
%175 = OpLabel
%23 = OpAccessChain %22 %21 %24
%25 = OpLoad %5 %23
%26 = OpShiftLeftLogical %5 %25 %27
%28 = OpIMul %5 %25 %29
%39 = OpFunctionCall %5 %33 %28 %40
%42 = OpAccessChain %41 %9 %24 %39
%43 = OpLoad %5 %42
%45 = OpIAdd %5 %39 %46
%44 = OpAccessChain %41 %9 %24 %45
%47 = OpLoad %5 %44
%49 = OpIAdd %5 %39 %50
%48 = OpAccessChain %41 %9 %24 %49
%51 = OpLoad %5 %48
%53 = OpIAdd %5 %39 %54
%52 = OpAccessChain %41 %9 %24 %53
%55 = OpLoad %5 %52
%57 = OpIAdd %5 %39 %40
%56 = OpAccessChain %41 %9 %24 %57
%58 = OpLoad %5 %56
%60 = OpIAdd %5 %39 %61
%59 = OpAccessChain %41 %9 %24 %60
%62 = OpLoad %5 %59
%64 = OpIAdd %5 %39 %27
%63 = OpAccessChain %41 %9 %24 %64
%65 = OpLoad %5 %63
%67 = OpCompositeConstruct %66 %43 %47 %51 %55 %58 %62 %65
%70 = OpBitcast %69 %67
%71 = OpBitwiseOr %5 %26 %72
%73 = OpIMul %5 %25 %29
%74 = OpIAdd %5 %73 %75
%76 = OpFunctionCall %5 %33 %74 %40
%77 = OpAccessChain %41 %9 %24 %76
%78 = OpLoad %5 %77
%80 = OpIAdd %5 %76 %46
%79 = OpAccessChain %41 %9 %24 %80
%81 = OpLoad %5 %79
%83 = OpIAdd %5 %76 %50
%82 = OpAccessChain %41 %9 %24 %83
%84 = OpLoad %5 %82
%86 = OpIAdd %5 %76 %54
%85 = OpAccessChain %41 %9 %24 %86
%87 = OpLoad %5 %85
%89 = OpIAdd %5 %76 %40
%88 = OpAccessChain %41 %9 %24 %89
%90 = OpLoad %5 %88
%92 = OpIAdd %5 %76 %61
%91 = OpAccessChain %41 %9 %24 %92
%93 = OpLoad %5 %91
%95 = OpIAdd %5 %76 %27
%94 = OpAccessChain %41 %9 %24 %95
%96 = OpLoad %5 %94
%97 = OpCompositeConstruct %66 %78 %81 %84 %87 %90 %93 %96
%98 = OpBitcast %69 %97
%100 = OpVectorShuffle %99 %70 %98 0 1 2 3 4 5 6 7 8 9 10 11 12 13 0 7
%101 = OpVectorShuffle %99 %70 %98 0 1 2 3 4 5 6 7 8 9 10 11 12 13 1 8
%102 = OpFunctionCall %5 %33 %25 %103
%104 = OpBitcast %14 %100
%105 = OpCompositeExtract %5 %104 0
%106 = OpCompositeExtract %5 %104 1
%107 = OpCompositeExtract %5 %104 2
%108 = OpCompositeExtract %5 %104 3
%109 = OpCompositeExtract %5 %104 4
%110 = OpCompositeExtract %5 %104 5
%111 = OpCompositeExtract %5 %104 6
%112 = OpCompositeExtract %5 %104 7
%113 = OpCompositeExtract %5 %104 8
%114 = OpCompositeExtract %5 %104 9
%115 = OpCompositeExtract %5 %104 10
%116 = OpCompositeExtract %5 %104 11
%117 = OpCompositeExtract %5 %104 12
%118 = OpCompositeExtract %5 %104 13
%119 = OpCompositeExtract %5 %104 14
%120 = OpCompositeExtract %5 %104 15
%121 = OpCompositeConstruct %14 %105 %106 %107 %108 %109 %110 %111 %112 %113 %114 %115 %116 %117 %118 %119 %120
%123 = OpAccessChain %122 %18 %24 %102
OpStore %123 %121
%124 = OpIAdd %5 %26 %125
%126 = OpIMul %5 %25 %29
%127 = OpIAdd %5 %126 %128
%129 = OpFunctionCall %5 %33 %127 %40
%130 = OpBitcast %66 %70
%131 = OpCompositeExtract %5 %130 0
%132 = OpCompositeExtract %5 %130 1
%133 = OpCompositeExtract %5 %130 2
%134 = OpCompositeExtract %5 %130 3
%135 = OpCompositeExtract %5 %130 4
%136 = OpCompositeExtract %5 %130 5
%137 = OpCompositeExtract %5 %130 6
%138 = OpAccessChain %41 %13 %24 %129
OpStore %138 %131
%140 = OpIAdd %5 %129 %46
%139 = OpAccessChain %41 %13 %24 %140
OpStore %139 %132
%142 = OpIAdd %5 %129 %50
%141 = OpAccessChain %41 %13 %24 %142
OpStore %141 %133
%144 = OpIAdd %5 %129 %54
%143 = OpAccessChain %41 %13 %24 %144
OpStore %143 %134
%146 = OpIAdd %5 %129 %40
%145 = OpAccessChain %41 %13 %24 %146
OpStore %145 %135
%148 = OpIAdd %5 %129 %61
%147 = OpAccessChain %41 %13 %24 %148
OpStore %147 %136
%150 = OpIAdd %5 %129 %27
%149 = OpAccessChain %41 %13 %24 %150
OpStore %149 %137
%151 = OpIAdd %5 %26 %152
%153 = OpIAdd %5 %25 %154
%155 = OpFunctionCall %5 %33 %153 %103
%156 = OpBitcast %14 %101
%157 = OpCompositeExtract %5 %156 0
%158 = OpCompositeExtract %5 %156 1
%159 = OpCompositeExtract %5 %156 2
%160 = OpCompositeExtract %5 %156 3
%161 = OpCompositeExtract %5 %156 4
%162 = OpCompositeExtract %5 %156 5
%163 = OpCompositeExtract %5 %156 6
%164 = OpCompositeExtract %5 %156 7
%165 = OpCompositeExtract %5 %156 8
%166 = OpCompositeExtract %5 %156 9
%167 = OpCompositeExtract %5 %156 10
%168 = OpCompositeExtract %5 %156 11
%169 = OpCompositeExtract %5 %156 12
%170 = OpCompositeExtract %5 %156 13
%171 = OpCompositeExtract %5 %156 14
%172 = OpCompositeExtract %5 %156 15
%173 = OpCompositeConstruct %14 %157 %158 %159 %160 %161 %162 %163 %164 %165 %166 %167 %168 %169 %170 %171 %172
%174 = OpAccessChain %122 %18 %24 %155
OpStore %174 %173
OpReturn
OpFunctionEnd
%33 = OpFunction %5 None %30
%31 = OpFunctionParameter %5
%32 = OpFunctionParameter %5
%34 = OpLabel
%35 = OpUDiv %5 %36 %32
%37 = OpBitwiseAnd %5 %31 %35
OpReturnValue %37
OpFunctionEnd

