; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 92
; Schema: 0
OpCapability Shader
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %9 %14 %18 %22 %25
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %12 "SSBO"
OpName %16 "SSBO"
OpName %20 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %11 ArrayStride 16
OpMemberDecorate %12 0 Offset 0
OpDecorate %12 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %14 DescriptorSet 0
OpDecorate %14 Binding 0
OpDecorate %14 NonWritable
OpDecorate %14 Restrict
OpDecorate %15 ArrayStride 4
OpMemberDecorate %16 0 Offset 0
OpDecorate %16 Block
OpDecorate %19 ArrayStride 16
OpMemberDecorate %20 0 Offset 0
OpDecorate %20 Block
OpDecorate %18 DescriptorSet 0
OpDecorate %18 Binding 0
OpDecorate %18 NonReadable
OpDecorate %18 Aliased
OpDecorate %22 DescriptorSet 0
OpDecorate %22 Binding 0
OpDecorate %22 NonReadable
OpDecorate %22 Aliased
OpDecorate %25 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeVector %5 4
%11 = OpTypeRuntimeArray %10
%12 = OpTypeStruct %11
%13 = OpTypePointer StorageBuffer %12
%14 = OpVariable %13 StorageBuffer
%15 = OpTypeRuntimeArray %5
%16 = OpTypeStruct %15
%17 = OpTypePointer StorageBuffer %16
%18 = OpVariable %17 StorageBuffer
%19 = OpTypeRuntimeArray %10
%20 = OpTypeStruct %19
%21 = OpTypePointer StorageBuffer %20
%22 = OpVariable %21 StorageBuffer
%23 = OpTypeVector %5 3
%24 = OpTypePointer Input %23
%25 = OpVariable %24 Input
%26 = OpTypePointer Input %5
%28 = OpConstant %5 0
%31 = OpConstant %5 2
%32 = OpTypePointer StorageBuffer %10
%40 = OpConstant %5 8
%41 = OpTypePointer StorageBuffer %5
%44 = OpConstant %5 4
%48 = OpConstant %5 5
%52 = OpConstant %5 6
%54 = OpTypeVector %5 7
%56 = OpTypeFloat 32
%57 = OpTypeVector %56 7
%60 = OpConstant %56 1
%61 = OpConstantComposite %57 %60 %60 %60 %60 %60 %60 %60
%81 = OpConstant %5 7
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %90
%90 = OpLabel
%27 = OpAccessChain %26 %25 %28
%29 = OpLoad %5 %27
%30 = OpIMul %5 %29 %31
%33 = OpAccessChain %32 %14 %28 %30
%34 = OpLoad %10 %33
%35 = OpCompositeExtract %5 %34 0
%36 = OpCompositeExtract %5 %34 1
%37 = OpCompositeExtract %5 %34 2
%38 = OpCompositeExtract %5 %34 3
%39 = OpIMul %5 %29 %40
%43 = OpIAdd %5 %39 %44
%42 = OpAccessChain %41 %9 %28 %43
%45 = OpLoad %5 %42
%47 = OpIAdd %5 %39 %48
%46 = OpAccessChain %41 %9 %28 %47
%49 = OpLoad %5 %46
%51 = OpIAdd %5 %39 %52
%50 = OpAccessChain %41 %9 %28 %51
%53 = OpLoad %5 %50
%55 = OpCompositeConstruct %54 %35 %36 %37 %38 %45 %49 %53
%58 = OpBitcast %57 %55
%59 = OpFAdd %57 %58 %61
%62 = OpIMul %5 %29 %31
%63 = OpBitcast %54 %59
%64 = OpCompositeExtract %5 %63 0
%65 = OpCompositeExtract %5 %63 1
%66 = OpCompositeExtract %5 %63 2
%67 = OpCompositeExtract %5 %63 3
%68 = OpCompositeExtract %5 %63 4
%69 = OpCompositeExtract %5 %63 5
%70 = OpCompositeExtract %5 %63 6
%71 = OpCompositeConstruct %10 %64 %65 %66 %67
%72 = OpAccessChain %32 %22 %28 %62
OpStore %72 %71
%73 = OpIMul %5 %29 %40
%75 = OpIAdd %5 %73 %44
%74 = OpAccessChain %41 %18 %28 %75
OpStore %74 %68
%77 = OpIAdd %5 %73 %48
%76 = OpAccessChain %41 %18 %28 %77
OpStore %76 %69
%79 = OpIAdd %5 %73 %52
%78 = OpAccessChain %41 %18 %28 %79
OpStore %78 %70
%80 = OpIMul %5 %29 %40
%82 = OpIAdd %5 %80 %81
%83 = OpAccessChain %41 %9 %28 %82
%84 = OpLoad %5 %83
%85 = OpBitcast %56 %84
%86 = OpIMul %5 %29 %40
%87 = OpIAdd %5 %86 %81
%88 = OpBitcast %5 %85
%89 = OpAccessChain %41 %18 %28 %87
OpStore %89 %88
OpReturn
OpFunctionEnd

