; SPIR-V
; Version: 1.6
; Generator: Unknown(30017); 21022
; Bound: 155
; Schema: 0
OpCapability Shader
OpCapability LongVectorEXT
OpExtension "SPV_EXT_long_vector"
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "main" %9 %13 %16
OpExecutionMode %3 LocalSize 1 1 1
OpName %3 "main"
OpName %7 "SSBO"
OpName %11 "SSBO"
OpDecorate %6 ArrayStride 4
OpMemberDecorate %7 0 Offset 0
OpDecorate %7 Block
OpDecorate %9 DescriptorSet 0
OpDecorate %9 Binding 0
OpDecorate %9 NonWritable
OpDecorate %9 Restrict
OpDecorate %10 ArrayStride 4
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 0
OpDecorate %13 NonReadable
OpDecorate %16 BuiltIn GlobalInvocationId
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeRuntimeArray %5
%7 = OpTypeStruct %6
%8 = OpTypePointer StorageBuffer %7
%9 = OpVariable %8 StorageBuffer
%10 = OpTypeRuntimeArray %5
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeVector %5 3
%15 = OpTypePointer Input %14
%16 = OpVariable %15 Input
%17 = OpTypePointer Input %5
%19 = OpConstant %5 0
%22 = OpConstant %5 17
%23 = OpTypePointer StorageBuffer %5
%28 = OpConstant %5 1
%32 = OpConstant %5 2
%36 = OpConstant %5 3
%40 = OpConstant %5 4
%44 = OpConstant %5 5
%48 = OpConstant %5 6
%52 = OpConstant %5 7
%56 = OpConstant %5 8
%60 = OpConstant %5 9
%64 = OpConstant %5 10
%68 = OpConstant %5 11
%72 = OpConstant %5 12
%76 = OpConstant %5 13
%80 = OpConstant %5 14
%84 = OpConstant %5 15
%86 = OpTypeVector %5 16
%88 = OpTypeFloat 32
%89 = OpTypeVector %88 16
%92 = OpConstant %88 1
%93 = OpConstantComposite %89 %92 %92 %92 %92 %92 %92 %92 %92 %92 %92 %92 %92 %92 %92 %92 %92
%144 = OpConstant %5 16
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %153
%153 = OpLabel
%18 = OpAccessChain %17 %16 %19
%20 = OpLoad %5 %18
%21 = OpIMul %5 %20 %22
%24 = OpAccessChain %23 %9 %19 %21
%25 = OpLoad %5 %24
%27 = OpIAdd %5 %21 %28
%26 = OpAccessChain %23 %9 %19 %27
%29 = OpLoad %5 %26
%31 = OpIAdd %5 %21 %32
%30 = OpAccessChain %23 %9 %19 %31
%33 = OpLoad %5 %30
%35 = OpIAdd %5 %21 %36
%34 = OpAccessChain %23 %9 %19 %35
%37 = OpLoad %5 %34
%39 = OpIAdd %5 %21 %40
%38 = OpAccessChain %23 %9 %19 %39
%41 = OpLoad %5 %38
%43 = OpIAdd %5 %21 %44
%42 = OpAccessChain %23 %9 %19 %43
%45 = OpLoad %5 %42
%47 = OpIAdd %5 %21 %48
%46 = OpAccessChain %23 %9 %19 %47
%49 = OpLoad %5 %46
%51 = OpIAdd %5 %21 %52
%50 = OpAccessChain %23 %9 %19 %51
%53 = OpLoad %5 %50
%55 = OpIAdd %5 %21 %56
%54 = OpAccessChain %23 %9 %19 %55
%57 = OpLoad %5 %54
%59 = OpIAdd %5 %21 %60
%58 = OpAccessChain %23 %9 %19 %59
%61 = OpLoad %5 %58
%63 = OpIAdd %5 %21 %64
%62 = OpAccessChain %23 %9 %19 %63
%65 = OpLoad %5 %62
%67 = OpIAdd %5 %21 %68
%66 = OpAccessChain %23 %9 %19 %67
%69 = OpLoad %5 %66
%71 = OpIAdd %5 %21 %72
%70 = OpAccessChain %23 %9 %19 %71
%73 = OpLoad %5 %70
%75 = OpIAdd %5 %21 %76
%74 = OpAccessChain %23 %9 %19 %75
%77 = OpLoad %5 %74
%79 = OpIAdd %5 %21 %80
%78 = OpAccessChain %23 %9 %19 %79
%81 = OpLoad %5 %78
%83 = OpIAdd %5 %21 %84
%82 = OpAccessChain %23 %9 %19 %83
%85 = OpLoad %5 %82
%87 = OpCompositeConstruct %86 %25 %29 %33 %37 %41 %45 %49 %53 %57 %61 %65 %69 %73 %77 %81 %85
%90 = OpBitcast %89 %87
%91 = OpFAdd %89 %90 %93
%94 = OpIMul %5 %20 %22
%95 = OpBitcast %86 %91
%96 = OpCompositeExtract %5 %95 0
%97 = OpCompositeExtract %5 %95 1
%98 = OpCompositeExtract %5 %95 2
%99 = OpCompositeExtract %5 %95 3
%100 = OpCompositeExtract %5 %95 4
%101 = OpCompositeExtract %5 %95 5
%102 = OpCompositeExtract %5 %95 6
%103 = OpCompositeExtract %5 %95 7
%104 = OpCompositeExtract %5 %95 8
%105 = OpCompositeExtract %5 %95 9
%106 = OpCompositeExtract %5 %95 10
%107 = OpCompositeExtract %5 %95 11
%108 = OpCompositeExtract %5 %95 12
%109 = OpCompositeExtract %5 %95 13
%110 = OpCompositeExtract %5 %95 14
%111 = OpCompositeExtract %5 %95 15
%112 = OpAccessChain %23 %13 %19 %94
OpStore %112 %96
%114 = OpIAdd %5 %94 %28
%113 = OpAccessChain %23 %13 %19 %114
OpStore %113 %97
%116 = OpIAdd %5 %94 %32
%115 = OpAccessChain %23 %13 %19 %116
OpStore %115 %98
%118 = OpIAdd %5 %94 %36
%117 = OpAccessChain %23 %13 %19 %118
OpStore %117 %99
%120 = OpIAdd %5 %94 %40
%119 = OpAccessChain %23 %13 %19 %120
OpStore %119 %100
%122 = OpIAdd %5 %94 %44
%121 = OpAccessChain %23 %13 %19 %122
OpStore %121 %101
%124 = OpIAdd %5 %94 %48
%123 = OpAccessChain %23 %13 %19 %124
OpStore %123 %102
%126 = OpIAdd %5 %94 %52
%125 = OpAccessChain %23 %13 %19 %126
OpStore %125 %103
%128 = OpIAdd %5 %94 %56
%127 = OpAccessChain %23 %13 %19 %128
OpStore %127 %104
%130 = OpIAdd %5 %94 %60
%129 = OpAccessChain %23 %13 %19 %130
OpStore %129 %105
%132 = OpIAdd %5 %94 %64
%131 = OpAccessChain %23 %13 %19 %132
OpStore %131 %106
%134 = OpIAdd %5 %94 %68
%133 = OpAccessChain %23 %13 %19 %134
OpStore %133 %107
%136 = OpIAdd %5 %94 %72
%135 = OpAccessChain %23 %13 %19 %136
OpStore %135 %108
%138 = OpIAdd %5 %94 %76
%137 = OpAccessChain %23 %13 %19 %138
OpStore %137 %109
%140 = OpIAdd %5 %94 %80
%139 = OpAccessChain %23 %13 %19 %140
OpStore %139 %110
%142 = OpIAdd %5 %94 %84
%141 = OpAccessChain %23 %13 %19 %142
OpStore %141 %111
%143 = OpIMul %5 %20 %22
%145 = OpIAdd %5 %143 %144
%146 = OpAccessChain %23 %9 %19 %145
%147 = OpLoad %5 %146
%148 = OpBitcast %88 %147
%149 = OpIMul %5 %20 %22
%150 = OpIAdd %5 %149 %144
%151 = OpBitcast %5 %148
%152 = OpAccessChain %23 %13 %19 %150
OpStore %152 %151
OpReturn
OpFunctionEnd

