ByteAddressBuffer Input : register(t0);
RWByteAddressBuffer Output : register(u0);
StructuredBuffer<vector<int, 7> > StructuredInput : register(t1);
RWStructuredBuffer<vector<int, 7> > StructuredOutput : register(u1);

[numthreads(1, 1, 1)]
void main(uint index : SV_DispatchThreadID)
{
	vector<int, 7> value = Input.Load<vector<int, 7> >(index * 28);
	Output.Store<vector<int, 7> >(index * 28, value + 1);
	StructuredOutput[index] = StructuredInput[index] - 1;
}
